sudo: required
services:
  - docker

before_install:
  - docker build -t 585859/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run 585859/react-test npm test -- --coverage

after_success:
  - docker build -t 585859/multi-client ./client 
  - docker build -t 585859/multi-nginx ./nginx
  - docker build -t 585859/multi-server ./server 
  - docker build -t 585859/multi-worker ./worker

  # Log into the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # take and push them to docker hub
  - docker push 585859/multi-client
  - docker push 585859/multi-nginx
  - docker push 585859/multi-server
  - docker push 585859/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "multi-docker"
  env: "MultiDocker-env
  bucket_name: "elasticbeanstalk-eu-west-1-864938016639"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"